# =====================================
# SuperHub config
# =====================================
# DO NOT CHANGE MANUALLY !!!
# IT IS CHANGED BY IN-GAME COMMAND
# =====================================
x: 0
y: 0
z: 0
world: world